### ISSUE TITLE
library does not work with android 4.2.2

### ISSUE THREAD

**Issue by ghost** [Prototik/HoloEverywhere#810]
hi
i,m developing with android 4.2.2
but the library just working with api level 19
is there any way to use the library for this version??
what should i do??
please help me...

**Comment by BraisGabin** [comment]
What don't work? Any log error? How can we reproduce this?

**Comment by ghost** [comment]
logcat error:

FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: android.support.v4.view.ViewCompatHC
at android.support.v4.view.ViewCompat$HCViewCompatImpl.resolveSizeAndState(ViewCompat.java:441)
at android.support.v4.view.ViewCompat.resolveSizeAndState(ViewCompat.java:1135)
at org.holoeverywhere.widget.LinearLayout.measureVertical(LinearLayout.java:848)
at org.holoeverywhere.widget.LinearLayout.onMeasure(LinearLayout.java:956)
at android.view.View.measure(View.java:15518)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)

you can see all errors here:
http://textuploader.com/13ec

**Comment by Prototik** [comment]
How you include library to your project?

**Comment by ghost** [comment]
properties -> Android -> Add
the library work fine in api 19
but in android 4.2.2 it's not work

**Comment by ghost** [comment]
please test the library on api level 17 (4.2.2) to see does the library work or not ...

**Comment by bazted** [comment]
Library is working in mine application from 2.2 till 4.4.2 or  from 7 api level till 19. All of them where tested on Genymotion emulators. Or maybe you are trying to build project with api sdk 17?

**Comment by Prototik** [comment]
Fuck, library working everywhere! Even on Android Wear (with broken skin in round variation, i know).
![screenshot from 2014-04-05 16 01 33](https://cloud.githubusercontent.com/assets/1416030/2622239/11d93756-bc9a-11e3-8536-654b4e75d59e.png)
I even not too lazy for searching my first android phone (se u20i, 4.1.2, ldpi, 2010 year motherfucker!):
![2014-04-05-160900](https://cloud.githubusercontent.com/assets/1416030/2622241/604c90f4-bc9a-11e3-9a60-774387d53d64.jpg)
![2014-04-05-160946](https://cloud.githubusercontent.com/assets/1416030/2622242/604e2874-bc9a-11e3-888c-3b6b23d4bb5d.jpg)
![device-2014-04-05-161050](https://cloud.githubusercontent.com/assets/1416030/2622243/70f4f3ec-bc9a-11e3-8cea-e8f4b1b2e3c9.png)

_btw genymotion is shit._

**Comment by ghost** [comment]
yeah, i'm trying to build project with api sdk 17

**Comment by bazted** [comment]
@Prototik, Genymotion runs faster than standard emulator and has features that I like(ex. Copy from Desktop & paste to device). Btw it's question of personal opinion.

 @hamedjj, try to use only the newest SDK and try to read wiki and ask questions on stackoverflow before opening issues.

 I understand angry of @Prototik. What did you think writing "not working" if you can see that project has more 2k stars. I won't think github society will star something that is not working. 

@Prototik thanks for great work.
