### ISSUE TITLE
problem with plugin 0.2.10 and 0.2.11 AND  typo with 'inhert' -> 'inherit'

### ISSUE THREAD

**Issue by Lakedaemon** [Prototik/HoloEverywhere#770]
My holoeverywhere config works with plugin 0.2.8.

Yet, it doesn't when I try to update to the plugin 0.2.10 or 0.2.11.
I followed the instructions in the wiki but was stuck with this error : 

```
A problem occurred configuring project ':core'.
> java.lang.NoSuchMethodError: org.apache.http.conn.ssl.SSLSocketFactory.<init>(Ljavax/net/ssl/SSLSocketFactory;Lorg/apache/http/conn/ssl/X509HostnameVerifier;)V
```

It seems like Ihave a httpclient related error. What can I do to fix it ?

Also, the 'inhert' setting for the supportV4 library might better be called
'inherit'  (typo ?)

**Comment by Prototik** [comment]
Fixed with 0.2.16 release.
