### ISSUE TITLE
Getting force close in FastScroll - All From Sliding Menu (Other/List) - Android 2.1 MDPI Emulator

### ISSUE THREAD

**Issue by ghost** [Prototik/HoloEverywhere#271]
Hi there,

I successfully integrated all libraries in Demo but When I am trying that demo on Android 2.1 MDPI Emulator, getting force close in Fast Scroll - All. (Other/List)

Project and Libraries Build using 4.1.2 as you did.

Log Trace: 

01-12 14:11:45.962: E/AndroidRuntime(569): Uncaught handler: thread main exiting due to uncaught exception
01-12 14:11:45.991: E/AndroidRuntime(569): java.lang.NoSuchMethodError: android.view.MotionEvent.getActionMasked
01-12 14:11:45.991: E/AndroidRuntime(569):  at org.holoeverywhere.widget.FastScroller.onInterceptTouchEvent(FastScroller.java:402)
01-12 14:11:45.991: E/AndroidRuntime(569):  at org.holoeverywhere.widget.ListView.onInterceptTouchEvent(ListView.java:442)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:803)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:822)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:822)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:822)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:822)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:822)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:822)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:822)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:822)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:822)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:822)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:822)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:822)
01-12 14:11:45.991: E/AndroidRuntime(569):  at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1659)
01-12 14:11:45.991: E/AndroidRuntime(569):  at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1107)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.app.Activity.dispatchTouchEvent(Activity.java:2061)
01-12 14:11:45.991: E/AndroidRuntime(569):  at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1643)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.view.ViewRoot.handleMessage(ViewRoot.java:1691)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.os.Handler.dispatchMessage(Handler.java:99)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.os.Looper.loop(Looper.java:123)
01-12 14:11:45.991: E/AndroidRuntime(569):  at android.app.ActivityThread.main(ActivityThread.java:4363)
01-12 14:11:45.991: E/AndroidRuntime(569):  at java.lang.reflect.Method.invokeNative(Native Method)
01-12 14:11:45.991: E/AndroidRuntime(569):  at java.lang.reflect.Method.invoke(Method.java:521)
01-12 14:11:45.991: E/AndroidRuntime(569):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
01-12 14:11:45.991: E/AndroidRuntime(569):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
01-12 14:11:45.991: E/AndroidRuntime(569):  at dalvik.system.NativeStart.main(Native Method)

Am I doing something wrong?

===============================Solved===========================================
Replace ev.getActionMasked() with ev.getAction() and it works perfectly fine. (FastScroller.java:401)

**Comment by ghost** [comment]
Updated.
