### ISSUE TITLE
Maven 1.3.3

### ISSUE THREAD

**Issue by imminent** [Prototik/HoloEverywhere#190]
I'm getting a compilation error:

```
getSharedPreferences(java.lang.String,int) in android.content.ContextWrapper cannot implement getSharedPreferences(java.lang.String,int) in com.WazaBe.HoloEverywhere.app.Base; attempting to use incompatible return type
[ERROR] found   : android.content.SharedPreferences
[ERROR] required: com.WazaBe.HoloEverywhere.preference.SharedPreferences
```

when I use the 1.3.3 release on Maven, I haven't been able to trace it down. Any ideas?

**Comment by agarwlGaurav** [comment]
Same as Issue #163

**Comment by 4nd3250n** [comment]
Can it be that you are trying to mix interface android.content.ContextWrapper with interface com.WazaBe.HoloEverywhere.app.Base.
They both have the abstract method getSharedPreferences(java.lang.String,int), yet those two abstract methods return different ypes. Former one returns android.content.SharedPreferences while the latter one one returns com.WazaBe.HoloEverywhere.preference.SharedPreferences.

I think this might be tracked down to using wrong import.

**Comment by agarwlGaurav** [comment]
@4nd3250n Where and how can we possible mix interface android.content.ContextWrapper with com.WazaBe.HoloEverywhere.app.Base?

**Comment by imminent** [comment]
I see, @CodingCrow the issues link back to something that implies that HoloEverywhere isn't currently compatible with support rev10, is that what the error is reflecting?

@4nd3250n if by "you" you mean @CodingCrow or myself, I only have the `Holo.*.Light` widgets defined as parents to my custom styles in a `style.xml`, and am not using anything from HoloEverywhere anywhere else. I can't perceive of a possible way that my code is causing the error, besides the fact it happens at compile time and only with code I don't modify (unpacked by Maven). I don't "import" a single object from HoloEverywhere.

**Comment by agarwlGaurav** [comment]
@imminent I could not figure out what is causing the error. If HoloEverywhere is not compatible with r10 then why is the problem only with Maven build not with default build of Intellij-Idea

**Comment by Prototik** [comment]
Which JDK are you use for compiling? I'm compile on JDK 1.7.0_09, everything ok.

**Comment by imminent** [comment]
I'm assuming you set that in the maven compiler plugin. Mine was 1.6. Trying
what you use.

**Comment by imminent** [comment]
Ok, I don't see any compilation errors now, though it was a non-trivial amount of work getting IntelliJ to use 1.7.

I set my maven-compiler-plugin like http://stackoverflow.com/questions/4724000/configure-maven-to-use-different-jdk-for-different-j2se-versions
Then I needed to set the Maven > Runner > JRE to JAVA_HOME (it's other options were 1.6 and Internal JRE)
Then I needed to get IntelliJ to see a JAVA_HOME environment variable. I ended up needing to run `launchctl setenv JAVA_HOME /Library/Java/JavaVirtualMachines/jdk1.7.0_09.jdk/Contents/Home` (I'm on a Mac), this comes from http://emmanuelbernard.com/blog/2012/05/09/setting-global-variables-intellij/ 

Let's see if that proves helpful for @CodingCrow before closing? Thanks for mentioning the JDK @Prototik

**Comment by imminent** [comment]
@Prototik do you have to do anything else when you use 1.7? I'm getting a runtime issue now, that Android can't find my Application class.

**Comment by imminent** [comment]
Do things like 

```
trouble processing:
[INFO] bad class file magic (cafebabe) or version (0033.0000)
[INFO] ...while parsing com/WazaBe/HoloEverywhere/widget/View.class
[INFO] ...while processing com/WazaBe/HoloEverywhere/widget/View.class
[INFO] 
[INFO] trouble processing:
[INFO] bad class file magic (cafebabe) or version (0033.0000)
[INFO] ...while parsing com/WazaBe/HoloEverywhere/widget/ViewGroup.class
[INFO] ...while processing com/WazaBe/HoloEverywhere/widget/ViewGroup.class
[INFO] 740 warnings
```

mean anything? There's a list of them in my logs

**Comment by imminent** [comment]
...I'm completely at a loss of words. I set my maven-compiler-plugin back to 1.6 and updated the plugin (and android-maven-plugin) to the lastest versions. Somehow something there resolved the issue, it seems. I have HoloEverywhere compiling and the app launches without crashing.

**Comment by agarwlGaurav** [comment]
@imminent Can you sum-up your, what should I be doing to get rid of this error?

**Comment by imminent** [comment]
Well, @CodingCrow, that's what I've been trying to do here. Try installing Java 7 (like @Prototik uses). Have your Maven > Runner use 1.7 (I had to do this through JAVA_HOME environment variable, details above). Leave you maven-compiler-plugin set for 1.6 (? not sure why I have to do it this way, but didn't work any other way for me), that's source and target. Maybe, check to make sure you're using android-maven-plugin 3.4.0 and maven-compiler-plugin 2.5.1. That's the best I can do to explain it.

**Comment by Prototik** [comment]
It's bug in 1.6 jdk. 1.7 compile correctly, but dalvik work only with 1.6 classes. Because target for maven-compiler-plugin should be 1.6, but compiler should be 1.7.

**Comment by imminent** [comment]
Thanks for explaining that @Prototik.

**Comment by agarwlGaurav** [comment]
@imminent Thanks.

**Comment by imminent** [comment]
I think it's safe to say this is a closed issue. Maybe how to avoid this problem should be documented in the instructions (if it is, I'm sorry I didn't see it anywhere). I will close the issue.

**Comment by noguess** [comment]
[ERROR] Failed to execute goal org.holoeverywhere:resbuilder:1.4.3-SNAPSHOT:build (default) on project library: Error in FileProcesser: java.lang.NullPointerException -> [Help 1]
[ERROR] 

why can't install with maven? Help!!!

**Comment by Prototik** [comment]
@noguess Update to latest master, run `mvn clean install` in resbuilder folder and try again.
If no - run maven with `-e` key for print stacktrace.
