### ISSUE TITLE
Activity with actionbar items crashes in 2.3.3, works in 4.4 - setShowAsAction, invalidateOptionsMenu

### ISSUE THREAD

**Issue by WilliamKensington** [Prototik/HoloEverywhere#718]
Hi!

Simple activity crashes in 2.3.

```
package com.example.holoeverywheretest;

import org.holoeverywhere.app.Activity;

import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.TextView;

public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        TextView text = (TextView) findViewById(R.id.text);
        text.setOnClickListener(new OnClickListener() {

            @Override
            public void onClick(View v) {
                invalidateOptionsMenu();
            }
        });
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        //getMenuInflater().inflate(R.menu.main, menu);
        menu.add(R.string.robo)
            .setIcon(R.drawable.ic_launcher)
            .setShowAsAction(MenuItem.SHOW_AS_ACTION_IF_ROOM)
            ;

        return true;
    }
}
```

Log (setShowAsAction):

12-09 19:27:57.516: D/dalvikvm(30327): GC_CONCURRENT freed 137K, 47% free 3021K/5639K, external 0K/0K, paused 2ms+3ms
12-09 19:27:57.706: I/dalvikvm(30327): Could not find method android.app.Application.startActivity, referenced from method org.holoeverywhere.app.Application.superStartActivity
12-09 19:27:57.706: W/dalvikvm(30327): VFY: unable to resolve virtual method 124: Landroid/app/Application;.startActivity (Landroid/content/Intent;Landroid/os/Bundle;)V
12-09 19:27:57.706: D/dalvikvm(30327): VFY: replacing opcode 0x6f at 0x0006
12-09 19:27:57.786: I/dalvikvm(30327): Could not find method android.content.Context.startActivity, referenced from method org.holoeverywhere.ThemeManager.startActivity
12-09 19:27:57.786: W/dalvikvm(30327): VFY: unable to resolve virtual method 250: Landroid/content/Context;.startActivity (Landroid/content/Intent;Landroid/os/Bundle;)V
12-09 19:27:57.786: D/dalvikvm(30327): VFY: replacing opcode 0x6e at 0x0032
12-09 19:27:57.786: D/dalvikvm(30327): VFY: dead code 0x0035-0035 in Lorg/holoeverywhere/ThemeManager;.startActivity (Landroid/content/Context;Landroid/content/Intent;ILandroid/os/Bundle;)V
12-09 19:27:57.816: I/dalvikvm(30327): Could not find method android.view.MenuItem.setShowAsAction, referenced from method com.example.holoeverywheretest.MainActivity.onCreateOptionsMenu
12-09 19:27:57.816: W/dalvikvm(30327): VFY: unable to resolve interface method 7074: Landroid/view/MenuItem;.setShowAsAction (I)V
12-09 19:27:57.816: D/dalvikvm(30327): VFY: replacing opcode 0x72 at 0x000f
12-09 19:27:57.816: D/dalvikvm(30327): VFY: dead code 0x0012-0012 in Lcom/example/holoeverywheretest/MainActivity;.onCreateOptionsMenu (Landroid/view/Menu;)Z
12-09 19:27:57.826: E/dalvikvm(30327): Could not find class 'android.test.mock.MockApplication', referenced from method android.support.v4.app._HoloActivity.onInit
12-09 19:27:57.826: W/dalvikvm(30327): VFY: unable to resolve instanceof 749 (Landroid/test/mock/MockApplication;) in Landroid/support/v4/app/_HoloActivity;
12-09 19:27:57.826: D/dalvikvm(30327): VFY: replacing opcode 0x20 at 0x0034
12-09 19:27:57.826: D/dalvikvm(30327): VFY: dead code 0x0036-0041 in Landroid/support/v4/app/_HoloActivity;.onInit (Landroid/support/v4/app/_HoloActivity$Holo;Landroid/os/Bundle;)V
12-09 19:27:57.826: D/dalvikvm(30327): VFY: dead code 0x006b-006c in Landroid/support/v4/app/_HoloActivity;.onInit (Landroid/support/v4/app/_HoloActivity$Holo;Landroid/os/Bundle;)V
12-09 19:27:57.836: I/dalvikvm(30327): Could not find method android.support.v7.app.ActionBarActivity.startActivityForResult, referenced from method android.support.v4.app._HoloActivity.superStartActivity
12-09 19:27:57.836: W/dalvikvm(30327): VFY: unable to resolve virtual method 4688: Landroid/support/v7/app/ActionBarActivity;.startActivityForResult (Landroid/content/Intent;ILandroid/os/Bundle;)V
12-09 19:27:57.836: D/dalvikvm(30327): VFY: replacing opcode 0x6f at 0x0006
12-09 19:27:57.926: I/dalvikvm(30327): Could not find method android.view.ViewStub.setLayoutInflater, referenced from method org.holoeverywhere.LayoutInflater._createView
12-09 19:27:57.926: W/dalvikvm(30327): VFY: unable to resolve virtual method 7416: Landroid/view/ViewStub;.setLayoutInflater (Landroid/view/LayoutInflater;)V
12-09 19:27:57.926: D/dalvikvm(30327): VFY: replacing opcode 0x6e at 0x0064
12-09 19:27:57.926: I/dalvikvm(30327): Could not find method android.view.LayoutInflater.getFactory2, referenced from method org.holoeverywhere.LayoutInflater.setParent
12-09 19:27:57.926: W/dalvikvm(30327): VFY: unable to resolve virtual method 7008: Landroid/view/LayoutInflater;.getFactory2 ()Landroid/view/LayoutInflater$Factory2;
12-09 19:27:57.926: D/dalvikvm(30327): VFY: replacing opcode 0x6e at 0x0027
12-09 19:27:57.926: D/dalvikvm(30327): VFY: dead code 0x002a-002f in Lorg/holoeverywhere/LayoutInflater;.setParent (Landroid/view/LayoutInflater;)Lorg/holoeverywhere/LayoutInflater;
12-09 19:27:57.936: E/ResourceType(30327): Style contains key with bad entry: 0x010102f0
12-09 19:27:58.086: D/szipinf(30327): Initializing inflate state
12-09 19:27:58.116: D/szipinf(30327): Initializing zlib to inflate
12-09 19:27:58.356: I/dalvikvm(30327): Could not find method android.view.View.getMeasuredState, referenced from method org.holoeverywhere.widget.LinearLayout.measureHorizontal
12-09 19:27:58.356: W/dalvikvm(30327): VFY: unable to resolve virtual method 7177: Landroid/view/View;.getMeasuredState ()I
12-09 19:27:58.356: D/dalvikvm(30327): VFY: replacing opcode 0x6e at 0x029f
12-09 19:27:58.356: I/dalvikvm(30327): Could not find method android.view.View.getMeasuredState, referenced from method org.holoeverywhere.widget.LinearLayout.measureHorizontal
12-09 19:27:58.356: W/dalvikvm(30327): VFY: unable to resolve virtual method 7177: Landroid/view/View;.getMeasuredState ()I
12-09 19:27:58.356: D/dalvikvm(30327): VFY: replacing opcode 0x6e at 0x0474
12-09 19:27:58.356: D/dalvikvm(30327): VFY: dead code 0x02a2-02a4 in Lorg/holoeverywhere/widget/LinearLayout;.measureHorizontal (II)V
12-09 19:27:58.356: D/dalvikvm(30327): VFY: dead code 0x0477-047c in Lorg/holoeverywhere/widget/LinearLayout;.measureHorizontal (II)V
12-09 19:27:58.366: I/dalvikvm(30327): Could not find method android.view.View.getMeasuredState, referenced from method org.holoeverywhere.widget.LinearLayout.measureVertical
12-09 19:27:58.366: W/dalvikvm(30327): VFY: unable to resolve virtual method 7177: Landroid/view/View;.getMeasuredState ()I
12-09 19:27:58.366: D/dalvikvm(30327): VFY: replacing opcode 0x6e at 0x020f
12-09 19:27:58.366: I/dalvikvm(30327): Could not find method android.view.View.getMeasuredState, referenced from method org.holoeverywhere.widget.LinearLayout.measureVertical
12-09 19:27:58.366: W/dalvikvm(30327): VFY: unable to resolve virtual method 7177: Landroid/view/View;.getMeasuredState ()I
12-09 19:27:58.366: D/dalvikvm(30327): VFY: replacing opcode 0x6e at 0x02f1
12-09 19:27:58.366: D/dalvikvm(30327): VFY: dead code 0x0212-0213 in Lorg/holoeverywhere/widget/LinearLayout;.measureVertical (II)V
12-09 19:27:58.366: D/dalvikvm(30327): VFY: dead code 0x02f4-02f7 in Lorg/holoeverywhere/widget/LinearLayout;.measureVertical (II)V
12-09 19:27:58.456: D/ATRecorder(30327): com.htc.autotest.dlib.RecordEngine in loader dalvik.system.DexClassLoader@405e0830
12-09 19:27:58.486: D/dalvikvm(30327): GC_CONCURRENT freed 252K, 46% free 3264K/6023K, external 0K/0K, paused 10ms+3ms
12-09 19:27:58.857: W/KeyCharacterMap(30327): Can't open keycharmap file
12-09 19:27:58.857: W/KeyCharacterMap(30327): Error loading keycharmap file '/system/usr/keychars/cy8c-touchscreen.kcm.bin'. hw.keyboards.65538.devname='cy8c-touchscreen'
12-09 19:27:58.877: I/KeyCharacterMap(30327): Using default keymap: /system/usr/keychars/qwerty.kcm.bin
12-09 19:27:58.877: D/AndroidRuntime(30327): Shutting down VM
12-09 19:27:58.877: W/dalvikvm(30327): threadid=1: thread exiting with uncaught exception (group=0x4001d648)
12-09 19:27:58.917: E/AndroidRuntime(30327): FATAL EXCEPTION: main
12-09 19:27:58.917: E/AndroidRuntime(30327): java.lang.NoSuchMethodError: android.view.MenuItem.setShowAsAction
12-09 19:27:58.917: E/AndroidRuntime(30327):    at com.example.holoeverywheretest.MainActivity.onCreateOptionsMenu(MainActivity.java:24)
12-09 19:27:58.917: E/AndroidRuntime(30327):    at android.app.Activity.onCreatePanelMenu(Activity.java:2290)
12-09 19:27:58.917: E/AndroidRuntime(30327):    at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:224)
12-09 19:27:58.917: E/AndroidRuntime(30327):    at android.support.v7.app.ActionBarActivity.superOnCreatePanelMenu(ActionBarActivity.java:211)
12-09 19:27:58.917: E/AndroidRuntime(30327):    at android.support.v7.app.ActionBarActivityDelegateBase$1.run(ActionBarActivityDelegateBase.java:62)
12-09 19:27:58.917: E/AndroidRuntime(30327):    at android.os.Handler.handleCallback(Handler.java:587)
12-09 19:27:58.917: E/AndroidRuntime(30327):    at android.os.Handler.dispatchMessage(Handler.java:92)
12-09 19:27:58.917: E/AndroidRuntime(30327):    at android.os.Looper.loop(Looper.java:143)
12-09 19:27:58.917: E/AndroidRuntime(30327):    at android.app.ActivityThread.main(ActivityThread.java:4293)
12-09 19:27:58.917: E/AndroidRuntime(30327):    at java.lang.reflect.Method.invokeNative(Native Method)
12-09 19:27:58.917: E/AndroidRuntime(30327):    at java.lang.reflect.Method.invoke(Method.java:507)
12-09 19:27:58.917: E/AndroidRuntime(30327):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
12-09 19:27:58.917: E/AndroidRuntime(30327):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
12-09 19:27:58.917: E/AndroidRuntime(30327):    at dalvik.system.NativeStart.main(Native Method)
12-09 19:28:01.950: I/Process(30327): Sending signal. PID: 30327 SIG: 9

But if i use menu resource like

```
<menu xmlns:android="http://schemas.android.com/apk/res/android" >
    <item
        android:id="@+id/action_settings"
        android:orderInCategory="100"
        android:showAsAction="ifRoom"
        android:icon="@drawable/ic_launcher"
        android:title="@string/action_settings"/>
</menu>
```

and

```
...
getMenuInflater().inflate(R.menu.main, menu);
...
```

it works.

invalidateOptionsMenu() crashes the activity too.

Log (invalidateOptionsMenu)

12-09 19:48:24.252: D/AndroidRuntime(32615): Shutting down VM
12-09 19:48:24.252: W/dalvikvm(32615): threadid=1: thread exiting with uncaught exception (group=0x4001d648)
12-09 19:48:24.262: E/AndroidRuntime(32615): FATAL EXCEPTION: main
12-09 19:48:24.262: E/AndroidRuntime(32615): java.lang.NoSuchMethodError: com.example.holoeverywheretest.MainActivity.invalidateOptionsMenu
12-09 19:48:24.262: E/AndroidRuntime(32615):    at com.example.holoeverywheretest.MainActivity$1.onClick(MainActivity.java:24)
12-09 19:48:24.262: E/AndroidRuntime(32615):    at android.view.View.performClick(View.java:2532)
12-09 19:48:24.262: E/AndroidRuntime(32615):    at android.view.View$PerformClick.run(View.java:9308)
12-09 19:48:24.262: E/AndroidRuntime(32615):    at android.os.Handler.handleCallback(Handler.java:587)
12-09 19:48:24.262: E/AndroidRuntime(32615):    at android.os.Handler.dispatchMessage(Handler.java:92)
12-09 19:48:24.262: E/AndroidRuntime(32615):    at android.os.Looper.loop(Looper.java:143)
12-09 19:48:24.262: E/AndroidRuntime(32615):    at android.app.ActivityThread.main(ActivityThread.java:4293)
12-09 19:48:24.262: E/AndroidRuntime(32615):    at java.lang.reflect.Method.invokeNative(Native Method)
12-09 19:48:24.262: E/AndroidRuntime(32615):    at java.lang.reflect.Method.invoke(Method.java:507)
12-09 19:48:24.262: E/AndroidRuntime(32615):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
12-09 19:48:24.262: E/AndroidRuntime(32615):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
12-09 19:48:24.262: E/AndroidRuntime(32615):    at dalvik.system.NativeStart.main(Native Method)

Problem is, i need to add/remove items dynamically using onPrepareOptionsMenu()/invalidateOptionsMenu(). Worked in 1.6.9-SNAPSHOT with ActionBarSherlock, stopped working in 2.1.1-SNAPSHOT.

Thanks in advance.

**Comment by Prototik** [comment]
invalidateOptionsMenu() -> supportInvalidateOptionsMenu()

``` java
MenuItemCompat.setShowAsAction(menu.add(R.string.robo), MenuItem.SHOW_AS_ACTION_IF_ROOM)
```

It's basic of support-v4 / appcompat-v7. Please read official android docs before reporting.
